//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerClientApplication.ClientUpdater {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/Contracts")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelular {
            get {
                return this.TelefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularField, value) != true)) {
                    this.TelefoneCelularField = value;
                    this.RaisePropertyChanged("TelefoneCelular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientUpdater.IClientUpdater")]
    public interface IClientUpdater {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientUpdater/UpdateClient", ReplyAction="http://tempuri.org/IClientUpdater/UpdateClientResponse")]
        void UpdateClient(PartnerClientApplication.ClientUpdater.Client client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientUpdater/UpdateClient", ReplyAction="http://tempuri.org/IClientUpdater/UpdateClientResponse")]
        System.Threading.Tasks.Task UpdateClientAsync(PartnerClientApplication.ClientUpdater.Client client);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientUpdaterChannel : PartnerClientApplication.ClientUpdater.IClientUpdater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientUpdaterClient : System.ServiceModel.ClientBase<PartnerClientApplication.ClientUpdater.IClientUpdater>, PartnerClientApplication.ClientUpdater.IClientUpdater {
        
        public ClientUpdaterClient() {
        }
        
        public ClientUpdaterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientUpdaterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientUpdaterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientUpdaterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateClient(PartnerClientApplication.ClientUpdater.Client client) {
            base.Channel.UpdateClient(client);
        }
        
        public System.Threading.Tasks.Task UpdateClientAsync(PartnerClientApplication.ClientUpdater.Client client) {
            return base.Channel.UpdateClientAsync(client);
        }
    }
}
